services:
  - type: web
    name: class-attendance-system
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    pythonVersion: 3.11.9
    envVars:
      - key: MONGO_URI
      - key: SECRET_KEY
    timeout: 900
